language: go

env:
  - GLIDE_DIR="/home/travis/gopath/src/github.com/Masterminds/glide" GO15VENDOREXPERIMENT=1

branches:
  only:
    - master

go:
  - 1.5.1

install:
  - git clone https://github.com/Masterminds/glide.git "$GLIDE_DIR"
  - pushd "$GLIDE_DIR"
  - make bootstrap build
  - popd
  - export PATH="$PATH:$GLIDE_DIR"

script: make bootstrap build test-charts
